# Generated by Django 6.0.2 on 2026-02-14 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_bus_bus_number_driverleave_emergencyalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='semester',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='fee',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('ARTS', 'Arts'), ('SCIENCE', 'Science'), ('DENTAL', 'Dental'), ('NURSING', 'Nursing'), ('ENGINEERING', 'Engineering'), ('COMMERCE', 'Commerce')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_status',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('ON_LEAVE', 'On Leave')], default='AVAILABLE', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='home_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
