# Generated by Django 6.0.2 on 2026-02-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='college_name',
            field=models.CharField(blank=True, choices=[('KSRCT', 'KSRCT'), ('KSRCE', 'KSRCE'), ('KSRCAS', 'KSRCAS'), ('KSRCAS (Women)', 'KSRCAS (Women)'), ('KSRDS', 'KSRDS'), ('KSRCN', 'KSRCN')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, choices=[('I', 'I Year'), ('II', 'II Year'), ('III', 'III Year'), ('IV', 'IV Year')], max_length=5, null=True),
        ),
    ]
