# Generated by Django 6.0.2 on 2026-02-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_user_department_user_college_name_user_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
