# Generated by Django 6.0.2 on 2026-02-16 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_bus_destination_latitude_bus_destination_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'On Leave'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=10)),
                ('km_driven', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'DRIVER'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_attendances', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'driver_attendances',
                'ordering': ['-date'],
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
