# Generated by Django 6.0.2 on 2026-02-16 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_driverattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REPLIED', 'Replied'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], default='OPEN', max_length=10)),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('is_satisfied', models.BooleanField(blank=True, null=True)),
                ('satisfaction_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='myapp.bus')),
                ('replied_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_queries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
